import Foundation

enum LocalizableStrings {
    static let appName = localized("app.name")
    static let loadingModel = localized("status.loading")
    static let ready = localized("status.ready")
    static let recording = localized("status.recording")
    static let transcribing = localized("status.transcribing")
    static let errorPrefix = localized("status.error")
    static let lastPrefix = localized("menu.last")
    static let settings = localized("menu.settings")
    static let quit = localized("menu.quit")
    static let copiedToClipboard = localized("output.copied")
    static let microphoneAccessRequired = localized("error.microphone_access")
    static let hotkey = localized("settings.hotkey")
    static let bridgePath = localized("settings.bridge_path")
    static let modelPath = localized("settings.model_path")
    static let status = localized("settings.status")
    static let modelLoaded = localized("settings.model_loaded")
    static let close = localized("settings.close")
    static let browse = localized("settings.browse")
    static let notConfigured = localized("settings.not_configured")
    static let bridgeNotConfigured = localized("error.bridge_not_configured")
    static let bridgeNotFound = localized("error.bridge_not_found")
    static let modelNotConfigured = localized("error.model_not_configured")
    static let modelNotFound = localized("error.model_not_found")
    static let engineNotReady = localized("error.engine_not_ready")
    static let engineCrashed = localized("error.engine_crashed")
    static let engineRestartFailed = localized("error.engine_restart_failed")
    static let transcriptionTimedOut = localized("error.transcription_timeout")
    static let requestInProgress = localized("error.request_in_progress")
    static let unexpectedBridgeResponse = localized("error.unexpected_response")
    static let modelLoadFailed = localized("error.model_load_failed")
    static let unknownError = localized("error.unknown")
    static let audioDeviceUnavailable = localized("error.audio_device_unavailable")
    static let noInputDevice = localized("error.no_input_device")
    static let audioConversionFailed = localized("error.audio_conversion")
    static let notRecording = localized("error.not_recording")
    static let noAudioCaptured = localized("error.no_audio")
    static let emptyTranscript = localized("error.empty_transcript")

    private static func localized(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: .module)
    }
}
